version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'api-service'
    restart: 'always'

    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'mysql-service'
    restart: 'always'

    volumes:
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./data/init:/docker-entrypoint-initdb.d/:rw
      - ./config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

