version: "3"

services:
  webserver:
    hostname: 'stgservices.muknow.com'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - mysql
  mysql:
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_STG}
      MYSQL_DATABASE: ${MYSQL_DATABASE_STG}
      MYSQL_USER: ${MYSQL_USER_STG}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD_STG}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-service'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_STG}
      MYSQL_USER: ${MYSQL_USER_STG}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_STG}
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
      
